/**
 * airtable-sync.js
 * Maps Chartex data → Florra CRM & Operations Hub (Airtable)
 *
 * Tables used:
 *   - Campaigns  (tblvbY12bVp1yudmp) — one monitoring campaign per run
 *   - People     (tblvkCqhZRjOjFYlT) — creators using Ebril's sounds
 *   - Moments    (tblURUYgvMRse3CFW) — song usage milestones / rising-sound alerts
 *
 * Set AIRTABLE_API_KEY and AIRTABLE_BASE_ID in your .env file.
 */

const https = require('https');

const BASE_ID = process.env.AIRTABLE_BASE_ID || 'applXEAjh6k3Xmybl';
const API_KEY = process.env.AIRTABLE_API_KEY;
const AT_BASE = 'https://api.airtable.com/v0';

// ── Table & Field IDs (Florra CRM & Operations Hub) ──────────────────────────

const TABLES = {
  people:    'tblvkCqhZRjOjFYlT',
  campaigns: 'tblvbY12bVp1yudmp',
  moments:   'tblURUYgvMRse3CFW',
};

const FIELDS = {
  // People
  fullName:          'fldwro19IuxtVwpS2',
  personType:        'fldM7iMLjDnowwgNk',  // "Creator"
  strategicRole:     'fldiyMBnszCdQC5ru',  // "Content Creator" | "Micro-Influencer"
  instagram:         'fldHwcL82xXmMQGAX',
  tikTok:            'fldhsnf6ulLtiFwey',
  youtube:           'fldcAKIGRWYTGGqZI',
  location:          'fldBn0L8ZAIIfKnhx',
  source:            'flda9AxkdQuhRrwqQ',  // "TikTok" | "Instagram" | "YouTube"
  relationshipStatus:'fldtavYCCwyAaKKEn',  // "New"
  relationshipTier:  'fld69WJYp8F0yxhEF',  // "Audience"
  relationshipStrength:'fld0o76wNr2wMmWVd',// "New"
  priority:          'fld6LApdoMiQYB2Ul',  // "High" | "Medium" | "Low"
  influenceScore:    'fldKSmlOzXOReV5k3',
  notes:             'flddBqyTNVz2RfEVW',

  // Campaigns
  campaignName:      'fldVhYfc3CChYNpah',
  campaignType:      'fldAxtmx1f5dad1mO',  // "Influencer Marketing"
  campaignStatus:    'fldSdu8KUP4eOf6Ky',  // "Active"
  campaignBrand:     'fldrgio6Ks6PAO6XX',  // "Ebril"
  campaignGoals:     'fldCODcSmKXz53AkC',
  campaignResults:   'fldMevXfwvaGekFaz',
  campaignNotes:     'fldhDQCTQ0XXTpFol',
  campaignUseCases:  'fld5cHRdm21kCWumA',  // ["Content Creation", "Social Media Promotion"]
  startDate:         'fldrxZ2voDp8Az1Nd',
  endDate:           'fld9N0ZTfFI1jOodc',

  // Moments
  momentDate:        'fldXHMr1ltGMSmEFE',
  momentDescription: 'fldhVwXU8v0FSXbD4',
  momentImpact:      'fldI2qaaUNLSZfdBK',  // "High" | "Medium" | "Low"
  momentBrandContext:'fld5ELxNCqQkA29jn',  // "Ebril"
  momentType:        'fldayZ2nj6HS2pE7G',  // "Media Feature" | "Marketing Campaign"
  momentNotes:       'fldx3td7kIzoAoRqh',
  momentPeople:      'fldFaiOYq798tMc44',
};

// ── HTTP helper ───────────────────────────────────────────────────────────────

function atRequest(method, path, body) {
  return new Promise((resolve, reject) => {
    const url = `${AT_BASE}/${BASE_ID}/${path}`;
    const payload = body ? JSON.stringify(body) : null;
    const parsed = new URL(url);

    const options = {
      hostname: parsed.hostname,
      path: parsed.pathname + parsed.search,
      method,
      headers: {
        Authorization: `Bearer ${API_KEY}`,
        'Content-Type': 'application/json',
        ...(payload ? { 'Content-Length': Buffer.byteLength(payload) } : {}),
      },
    };

    const req = https.request(options, (res) => {
      let data = '';
      res.on('data', (c) => (data += c));
      res.on('end', () => {
        if (res.statusCode >= 400) {
          return reject(new Error(`Airtable ${res.statusCode}: ${data}`));
        }
        try { resolve(JSON.parse(data)); }
        catch (e) { reject(new Error(`Parse error: ${data}`)); }
      });
    });

    req.on('error', reject);
    if (payload) req.write(payload);
    req.end();
  });
}

function createRecords(tableId, records) {
  // Airtable accepts max 10 records per request
  const chunks = [];
  for (let i = 0; i < records.length; i += 10) chunks.push(records.slice(i, i + 10));
  return Promise.all(chunks.map((chunk) => atRequest('POST', tableId, { records: chunk })));
}

// ── Domain mappers ────────────────────────────────────────────────────────────

/**
 * Build a Campaigns record for the current sync run.
 */
function buildMonitoringCampaign(runDate, trackCount) {
  return {
    fields: {
      [FIELDS.campaignName]:    `Chartex Sound Monitor — ${runDate}`,
      [FIELDS.campaignType]:    'Influencer Marketing',
      [FIELDS.campaignStatus]:  'Active',
      [FIELDS.campaignBrand]:   'Ebril',
      [FIELDS.campaignGoals]:   `Track usage of Ebril's catalog across TikTok, Spotify, YouTube, and Shazam.\nIdentify creators driving each sound and surface rising independent artists.`,
      [FIELDS.campaignUseCases]:['Content Creation', 'Social Media Promotion'],
      [FIELDS.startDate]:       new Date().toISOString(),
      [FIELDS.campaignNotes]:   `Auto-generated by chartex-airtable-sync.\nTracks monitored: ${trackCount}`,
    },
  };
}

/**
 * Map a Chartex creator record → People row.
 * Only creates new entries; dedup by username+platform should be done upstream.
 */
function buildCreatorPerson(creator, songTitle) {
  const platform = (creator.platform || '').toLowerCase();
  const isHighInfluence = creator.influenceScore >= 70 || creator.followers >= 100_000;
  const priority = isHighInfluence ? 'High' : creator.followers >= 10_000 ? 'Medium' : 'Low';

  return {
    fields: {
      [FIELDS.fullName]:           creator.username,
      [FIELDS.personType]:         'Creator',
      [FIELDS.strategicRole]:      creator.followers >= 100_000 ? 'Influencer' : 'Content Creator',
      ...(platform === 'tiktok'    ? { [FIELDS.tikTok]:    `@${creator.username}` } : {}),
      ...(platform === 'instagram' ? { [FIELDS.instagram]: `@${creator.username}` } : {}),
      ...(platform === 'youtube'   ? { [FIELDS.youtube]:   creator.username       } : {}),
      ...(creator.country          ? { [FIELDS.location]:  creator.country        } : {}),
      [FIELDS.source]:             platform === 'tiktok' ? 'TikTok' :
                                   platform === 'instagram' ? 'Instagram' :
                                   platform === 'youtube'   ? 'YouTube' : 'Organic',
      [FIELDS.relationshipStatus]: 'New',
      [FIELDS.relationshipTier]:   'Audience',
      [FIELDS.relationshipStrength]:'New',
      [FIELDS.priority]:           priority,
      [FIELDS.influenceScore]:     creator.influenceScore || Math.round((creator.followers || 0) / 1000),
      [FIELDS.notes]:
        `Discovered via Chartex — using "${songTitle}" as a sound.\n` +
        `Posts with track: ${creator.postCount || '?'} | Followers: ${(creator.followers || 0).toLocaleString()} | ` +
        `Avg views: ${(creator.avgViews || 0).toLocaleString()}\n` +
        `First used: ${creator.firstUsed || '?'} | Latest post: ${creator.latestPost || '?'}`,
    },
  };
}

/**
 * Map a Chartex song-usage snapshot → Moments row (usage milestone).
 */
function buildUsageMoment(track, usage, creatorRecordIds = []) {
  const tiktok = usage.tiktok || {};
  const spotify = usage.spotify || {};
  const trend = tiktok.trend || spotify.trend || 'stable';
  const impact =
    tiktok.weeklyVelocity >= 10000 || spotify.monthlyVelocity >= 50000
      ? 'High'
      : tiktok.weeklyVelocity >= 1000
      ? 'Medium'
      : 'Low';

  return {
    fields: {
      [FIELDS.momentDate]:        new Date().toISOString(),
      [FIELDS.momentBrandContext]:'Ebril',
      [FIELDS.momentType]:        'Marketing Campaign',
      [FIELDS.momentImpact]:      impact,
      [FIELDS.momentDescription]:
        `Chartex snapshot for "${track.title}"\n\n` +
        `TikTok sound uses: ${(tiktok.soundUses || 0).toLocaleString()} (+${tiktok.weeklyVelocity || 0}/wk, trend: ${trend})\n` +
        `Spotify streams: ${(spotify.streams || 0).toLocaleString()} (+${spotify.monthlyVelocity || 0}/mo)\n` +
        `YouTube views: ${((usage.youtube || {}).views || 0).toLocaleString()}\n` +
        `Shazam searches: ${((usage.shazam || {}).searches || 0).toLocaleString()}\n` +
        `Apple Music plays: ${((usage.appleMusic || {}).plays || 0).toLocaleString()}`,
      [FIELDS.momentNotes]:
        `ISRC: ${track.isrc || '?'} | Released: ${track.releaseDate || '?'}\n` +
        `Last updated: ${usage.lastUpdated || new Date().toISOString()}`,
      ...(creatorRecordIds.length ? { [FIELDS.momentPeople]: creatorRecordIds } : {}),
    },
  };
}

/**
 * Map a Chartex rising-sound entry → Moments row (discovery alert).
 */
function buildRisingSoundMoment(sound) {
  const impact = sound.velocityScore >= 80 ? 'High' : sound.velocityScore >= 50 ? 'Medium' : 'Low';

  return {
    fields: {
      [FIELDS.momentDate]:        new Date().toISOString(),
      [FIELDS.momentBrandContext]:'Ebril',
      [FIELDS.momentType]:        'Media Feature',
      [FIELDS.momentImpact]:      impact,
      [FIELDS.momentDescription]:
        `Rising Sound Alert: "${sound.title}" by ${sound.artistName}\n\n` +
        `Velocity Score: ${sound.velocityScore || '?'} | Weekly growth: +${sound.weeklyGrowthPct || 0}%\n` +
        `Label: ${sound.label || 'Independent'} | Independent: ${sound.isIndependent ? 'Yes' : 'No'}\n` +
        `Top creator: ${sound.topCreator || '?'}\n` +
        `Active platforms: ${(sound.platforms || []).join(', ')}`,
      [FIELDS.momentNotes]:
        `Source: Chartex Trending Sounds feed\n` +
        `Opportunity: Possible collab, remix, or trend-hop. Reach out to top creator.`,
    },
  };
}

/**
 * Map a rising creator from Chartex → People row.
 */
function buildRisingCreatorPerson(creator) {
  const platform = (creator.platform || '').toLowerCase();

  return {
    fields: {
      [FIELDS.fullName]:           creator.username,
      [FIELDS.personType]:         'Creator',
      [FIELDS.strategicRole]:      creator.followers >= 100_000 ? 'Influencer' : 'Micro-Influencer',
      ...(platform === 'tiktok'    ? { [FIELDS.tikTok]:    `@${creator.username}` } : {}),
      ...(platform === 'instagram' ? { [FIELDS.instagram]: `@${creator.username}` } : {}),
      ...(platform === 'youtube'   ? { [FIELDS.youtube]:   creator.username       } : {}),
      ...(creator.country          ? { [FIELDS.location]:  creator.country        } : {}),
      [FIELDS.source]:             platform === 'tiktok' ? 'TikTok' :
                                   platform === 'instagram' ? 'Instagram' : 'YouTube',
      [FIELDS.relationshipStatus]: 'New',
      [FIELDS.relationshipTier]:   'Prospect',
      [FIELDS.relationshipStrength]:'New',
      [FIELDS.priority]:           creator.weeklyFollowerGrowth >= 5000 ? 'High' : 'Medium',
      [FIELDS.influenceScore]:     Math.round((creator.avgEngagementRate || 0) * 10),
      [FIELDS.notes]:
        `Rising Creator — surfaced by Chartex Trending feed.\n` +
        `Followers: ${(creator.followers || 0).toLocaleString()} | +${creator.weeklyFollowerGrowth || 0}/wk\n` +
        `Avg engagement: ${creator.avgEngagementRate || 0}%\n` +
        `Top sound: ${creator.topSound || '?'} | Genre: ${creator.genre || '?'}`,
    },
  };
}

// ── Main sync function ────────────────────────────────────────────────────────

/**
 * Sync Chartex data to Airtable.
 *
 * @param {Array}  ebrilSnapshots   — from ChartexClient.getEbrilSnapshot()
 * @param {Array}  risingSounds     — from ChartexClient.getRisingSounds()
 * @param {Array}  risingCreators   — from ChartexClient.getRisingCreators()
 */
async function syncToAirtable(ebrilSnapshots, risingSounds, risingCreators) {
  const runDate = new Date().toISOString().split('T')[0];
  const log = (msg) => console.log(`[airtable-sync] ${msg}`);

  // 1. Create monitoring campaign
  log('Creating monitoring campaign…');
  const [campaignResult] = await createRecords(TABLES.campaigns, [
    buildMonitoringCampaign(runDate, ebrilSnapshots.length),
  ]);
  log(`Campaign created: ${campaignResult.records[0].id}`);

  // 2. Upsert creators who are using Ebril's sounds → People
  log('Syncing creators using Ebril sounds…');
  const creatorPersonMap = {};  // username → airtable record id

  for (const snapshot of ebrilSnapshots) {
    if (!snapshot.creators.length) continue;
    const personRecords = snapshot.creators.map((c) =>
      buildCreatorPerson(c, snapshot.track.title)
    );
    const results = await createRecords(TABLES.people, personRecords);
    results.forEach((res) => {
      res.records.forEach((rec, i) => {
        const username = snapshot.creators[i]?.username;
        if (username) creatorPersonMap[username] = rec.id;
      });
    });
  }
  log(`Synced ${Object.keys(creatorPersonMap).length} creator people records.`);

  // 3. Create usage moment for each Ebril track
  log('Creating song usage moments…');
  for (const snapshot of ebrilSnapshots) {
    const creatorIds = snapshot.creators
      .map((c) => creatorPersonMap[c.username])
      .filter(Boolean);
    await createRecords(TABLES.moments, [
      buildUsageMoment(snapshot.track, snapshot.usage, creatorIds),
    ]);
  }
  log(`Created ${ebrilSnapshots.length} usage moment(s).`);

  // 4. Add rising sounds as discovery alerts
  log('Creating rising sound alert moments…');
  if (risingSounds.length) {
    await createRecords(
      TABLES.moments,
      risingSounds.map(buildRisingSoundMoment)
    );
  }
  log(`Created ${risingSounds.length} rising sound alert(s).`);

  // 5. Add rising creators to People
  log('Syncing rising creators…');
  if (risingCreators.length) {
    await createRecords(
      TABLES.people,
      risingCreators.map(buildRisingCreatorPerson)
    );
  }
  log(`Synced ${risingCreators.length} rising creator(s).`);

  log('Sync complete.');
  return {
    campaign: campaignResult.records[0].id,
    creatorsSynced: Object.keys(creatorPersonMap).length,
    usageMoments: ebrilSnapshots.length,
    risingSoundAlerts: risingSounds.length,
    risingCreatorsSynced: risingCreators.length,
  };
}

module.exports = {
  syncToAirtable,
  buildMonitoringCampaign,
  buildCreatorPerson,
  buildUsageMoment,
  buildRisingSoundMoment,
  buildRisingCreatorPerson,
  TABLES,
  FIELDS,
};
